export const ROUTES = {
  MAIN: '/',
  NOT_FOUND: '/not-found',
  AUTH: '/auth',
  SEARCH: '/search',
  CREATE_POST: '/createpost',
  USER_EDIT: '/my/:id',
  USER_PROFILE: '/users/:userId',
  USER_LIST: '/user',
  CHAT_LIST: '/chat',
  CHAT: '/chat/:chatId',
  USER_INFO: (userId: string) => `users/${userId}`,
  FOLLOW_BY_USER_ID: (userId: string) => `/follow/${userId}`,
  FOLLOWER_BY_USER_ID: (userId: string) => `/follower/${userId}`,
};
